

services:
  bank-demo:
    container_name: bank-prod
    build:
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bank-demo-db:5432/demo-bank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - bank-demo-db
      - redis
    networks:
      - common

  bank-demo-db:
    container_name: bank-db
    image: postgres:latest
    environment:
      POSTGRES_DB: demo-bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - '5491:5432'
    networks:
      - common
    volumes:
      - bank-demo-db-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - common
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - common


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - common
    environment:
      - REDIS_PASSWORD=default
    volumes:
      - redis-data:/data
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
        - common
    depends_on:
      - redis

networks:
  common:
    driver: bridge

volumes:
  redis-data:
  bank-demo-db-data:
    driver: local
